Repository Kaiak/kaiak-wallet, pull requests merged in 2021-01, with the labels that each got.

#161 README: various typo fixes
  README.md
Labels: documentation

#160 Possible to update in send
  src/view/wallet/Send.svelte
Labels: enhancement

#162 Use bignumber
  .github/workflows/release.yml
  .github/workflows/yarn.yml
  jest.config.js
  package.json
  src/__tests__/test-number-functions.spec.ts
  src/machinery/nanocurrency-web-wrapper.ts
  src/machinery/text-utils.ts
  src/view/wallet/Account.svelte
  src/view/wallet/Send.svelte
  tsconfig.json
  yarn.lock
Labels: bug

#166 Merge gone wrong
  src/view/wallet/Send.svelte
Labels: bug

#167 On update in Send, keep toAddress
  src/machinery/WalletState.ts
  src/view/wallet/Send.svelte
Labels: bug

#169 Adds translation to Farsi
  README.md
  public/index.html
  public/locales/fa.properties
  public/manifest.json
Labels: localization

#173 Adds translation to Brazilian Portuguese
  README.md
  public/index.html
  public/locales/pt-BR.properties
  public/manifest.json
Labels: localization

#174 Default to regular seed
  package.json
  src/machinery/wallet.ts
  yarn.lock
Labels: enhancement

#175 Moves global CSS into respective components.
  public/css/kaiui.css
  public/index.html
  src/App.svelte
  src/components/Button.svelte
  src/components/Content.svelte
  src/components/Link.svelte
  src/components/List.svelte
  src/components/Text.svelte
  src/components/Title.svelte
  src/components/Toast.svelte
  src/components/input/LabelInput.svelte
  src/components/input/NumberInput.svelte
  src/components/input/TextArea.svelte
  src/components/input/TextInput.svelte
  src/components/list/ListItem.svelte
  src/components/list/Primary.svelte
  src/components/list/WithSecondary.svelte
  src/view/SoftwareKeys.svelte
Labels: enhancement

#176 Don't attach window events on alternative load
  public/index.html
  src/main.ts
Labels: enhancement

#179 toAddress must be mutable
  src/view/wallet/Send.svelte
Labels: bug
